version: "3.1"
services:
  app:
    container_name: trackerms-api
    image: spring-boot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - trilockdb
  trilockdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=palomino17iag
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trackable

