version: "3.1"
services:
  trilock:
    container_name: trilock-api
    image: trilock
    build: ./
    ports:
      - "8085:8085"
    depends_on:
      - trilockdb
  trilockdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=palomino17iag
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trackable

